// src/asset-assignments/sampleAssignments.ts
import { AssetAssignment } from "./AssetAssignmentTable";

export default function sampleAssignments(): AssetAssignment[] {
  return [
    {
      id: "assign-1",
      number: "AST-001",
      description: "Dummy description",
      employeeId: "EMP-123",
      employeeName: "Ahmed Al-Rashid",
      role: "Inspector",
      assignedDate: new Date("2024-01-15"),
      expectedDate: new Date("2024-01-25"),
      status: "In Progress",
    },
    {
      id: "assign-2",
      number: "AST-001",
      description: "Dummy description",
      employeeId: "EMP-123",
      employeeName: "Ahmed Al-Rashid",
      role: "Inspector",
      assignedDate: new Date("2024-01-15"),
      expectedDate: new Date("2024-01-25"),
      status: "In Progress",
    },
    {
      id: "assign-3",
      number: "AST-001",
      description: "Dummy description",
      employeeId: "EMP-123",
      employeeName: "Ahmed Al-Rashid",
      role: "Inspector",
      assignedDate: new Date("2024-01-15"),
      expectedDate: new Date("2024-01-25"),
      status: "In Progress",
    },
    {
      id: "assign-4",
      number: "AST-001",
      description: "Dummy description",
      employeeId: "EMP-123",
      employeeName: "Ahmed Al-Rashid",
      role: "Inspector",
      assignedDate: new Date("2024-01-15"),
      expectedDate: new Date("2024-01-25"),
      status: "In Progress",
    },
    {
      id: "assign-5",
      number: "AST-001",
      description: "Dummy description",
      employeeId: "EMP-123",
      employeeName: "Ahmed Al-Rashid",
      role: "Inspector",
      assignedDate: new Date("2024-01-15"),
      expectedDate: new Date("2024-01-25"),
      status: "In Progress",
    },
    {
      id: "assign-6",
      number: "AST-001",
      description: "Dummy description",
      employeeId: "EMP-123",
      employeeName: "Ahmed Al-Rashid",
      role: "Inspector",
      assignedDate: new Date("2024-01-15"),
      expectedDate: new Date("2024-01-25"),
      status: "In Progress",
    },
    {
      id: "assign-7",
      number: "AST-001",
      description: "Dummy description",
      employeeId: "EMP-123",
      employeeName: "Ahmed Al-Rashid",
      role: "Inspector",
      assignedDate: new Date("2024-01-15"),
      expectedDate: new Date("2024-01-25"),
      status: "In Progress",
    },
    {
      id: "assign-8",
      number: "AST-001",
      description: "Dummy description",
      employeeId: "EMP-123",
      employeeName: "Ahmed Al-Rashid",
      role: "Inspector",
      assignedDate: new Date("2024-01-15"),
      expectedDate: new Date("2024-01-25"),
      status: "In Progress",
    },
  ];
}
